### ISSUE TITLE
Configure chat

### ISSUE THREAD

**Issue by mohsinalimat** [codescientist703/frappe_chat#1]
How to configure chat and open chat window?

**Comment by codescientist703** [comment]
Hello, this is an ongoing project and will be completed most probably by end of the month.

**Comment by mohsinalimat** [comment]
Great to hear 👍👏

**Comment by mohsinalimat** [comment]
I can not see any chat icon in navbar and the latest frappe chat code.

![Screenshot 2021-09-09 at 5 59 08 PM](https://user-images.githubusercontent.com/973676/132685800-083c0e9f-d258-4b0d-b826-75a573d082ee.png)
