### ISSUE TITLE
No chat icon on navbar

### ISSUE THREAD

**Issue by mohsinalimat** [codescientist703/frappe_chat#2]
I am excited to use this feature but I can not see any chat icon in the navbar and the latest frappe chat code.

![](https://user-images.githubusercontent.com/973676/132685800-083c0e9f-d258-4b0d-b826-75a573d082ee.png)

**Comment by codescientist703** [comment]
what error are you getting in the console?

**Comment by mohsinalimat** [comment]
Before installation

It is important to delete all the deprecated doctypes of the existing chat application in the framework.

To accomplish that, you would have to delete all the doctypes which has the prefix chat.


What I have delete?

**Comment by mohsinalimat** [comment]
> what error are you getting in the console?

![Screenshot 2021-09-10 at 10 40 35 AM](https://user-images.githubusercontent.com/973676/132802927-78da87e1-0ecc-48af-83e7-bb4b322eb37c.png)

**Comment by mohsinalimat** [comment]
Can not see any chat icon li CSS in the below screenshots.

![Screenshot 2021-09-10 at 4 52 59 PM](https://user-images.githubusercontent.com/973676/132846182-12ae16f8-1abd-450e-ba86-c404f822c758.png)

**Comment by codescientist703** [comment]
That's because you are using the old version of Frappe that does not include the bundling of assets. You have to update to develop branch frappe version.

**Comment by mohsinalimat** [comment]
It's working in develop branch.

One issue is there when userA sent message to userB then at a time userB can not get the message.

UserB have to close the chat and open again then get new message.

**Comment by codescientist703** [comment]
Please raise a new issue for this including screenshots, tracebacks, and console errors.
