### ISSUE TITLE
Can not get the new message

### ISSUE THREAD

**Issue by mohsinalimat** [codescientist703/frappe_chat#3]
One issue is there when userA sent a message to userB then at a time userB can not get the message.

UserB has to close the chat and open again then get a new message.

**Comment by codescientist703** [comment]
If UserA and UserB are the same, only 1 session user will get the message.

**Comment by mohsinalimat** [comment]
UserA uses the normal window and UserB uses the Private window.

**Comment by codescientist703** [comment]
UserA and UserB should be **different**.

**Comment by mohsinalimat** [comment]
Yes

**Comment by codescientist703** [comment]
Post a screenshot showing it along with the open Inspect element console.

**Comment by mohsinalimat** [comment]
Please check

https://user-images.githubusercontent.com/973676/133729334-0640798d-18bf-47ac-b2b1-8f72446c21e0.mov

**Comment by codescientist703** [comment]
seems like your socketio server is not working correctly. I have tested it on a fresh new site and it works perfectly fine.

**Comment by codescientist703** [comment]
It should work. If you are not receiving messages then there is most likely a problem with your socketio configuration.

**Comment by hamzahabeeb** [comment]
doesnt work
